displayName=Stymphike Hunter
author=JoadsV
description=Notifies you when you catch a stymphike and marks the trees you have baited.
tags=hunter,stymphike,vampyrium,bait,bird
version=
plugins=com.stymphike.StymphikePlugin
build=standard
